// TAQA Knowledge Hub — flat search index (all 11 segments, all doc types)
// Used by ai-search.html for instant cross-segment results
const TAQA_SEARCH_INDEX=(function(){
  var S=[
    // ── Coiled Tubing ──────────────────────────────────────────────
    {t:'CT-001 Pre-Job Safety Checklist',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-002 BHA Assembly Procedure',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-003 Well Entry Protocol',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-004 Emergency Disconnect Procedure',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-005 Pressure Testing Procedure',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-006 CT Unit Rig-Up & Rig-Down',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-007 Nitrogen Injection SOP',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-008 Milling Operations SOP',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-009 Acid Stimulation SOP',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-010 Fishing Operations SOP',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-011 Logging While CT SOP',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT-012 Post-Job Reporting SOP',tp:'sop',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT Unit Maintenance Manual v3.2',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'BHA Component Reference Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Injector Head Operations Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Control Cabin Systems Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT String Inspection Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Crane & Rigging Safety Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Chemical Handling Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Data Acquisition Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT Wellhead Equipment Manual',tp:'manual',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT Operations Authorization Policy',tp:'policy',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Equipment Certification Policy',tp:'policy',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Crew Competency Requirements',tp:'policy',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Environmental Compliance Policy',tp:'policy',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CT Asset Management Policy',tp:'policy',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Incident Reporting Policy',tp:'policy',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'ALERT-CT-001: BHA connector fatigue — inspect all units before next run',tp:'alert',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'ALERT-CT-002: New pressure rating for 2-inch CT string — effective immediately',tp:'alert',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'ALERT-CT-003: Chemical compatibility update for H2S environments',tp:'alert',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'LL-CT-001: Near-miss during CT rig-up — lessons from H2 field',tp:'lesson',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'LL-CT-002: CT string failure analysis — root cause and prevention',tp:'lesson',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'LL-CT-003: Lessons from coiled tubing fishing operation',tp:'lesson',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'LL-CT-004: Mud motor stall — diagnosis and recovery',tp:'lesson',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'LL-CT-005: Pressure integrity test failure — field findings',tp:'lesson',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'Orion CT Control System v2.3',tp:'software',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'WellPlan CT Simulator v4.1',tp:'software',s:'coiled-tubing',sn:'Coiled Tubing'},
    {t:'CoilScan Inspection Reporter v1.8',tp:'software',s:'coiled-tubing',sn:'Coiled Tubing'},
    // ── Fracturing ─────────────────────────────────────────────────
    {t:'FRAC-001 Pre-Job Safety Meeting',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-002 Pump Rig-Up Procedure',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-003 Iron Pressure Test',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-004 Fluid Mixing SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-005 Proppant Handling SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-006 Treatment Execution SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-007 Emergency Shutdown Procedure',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-008 Post-Job Flowback SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-009 Multi-Stage Frac SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-010 Acid Pre-Flush SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-011 Chemical Additive SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-012 Wellhead Connection SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-013 Data Van Operations SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-014 Blender Operations SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-015 Iron Inspection SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-016 Night Operations SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-017 Screen-Out Response SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'FRAC-018 Post-Job Cleanup SOP',tp:'sop',s:'fracturing',sn:'Fracturing'},
    {t:'Hydraulic Fracturing Design Manual v4.1',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Pump Unit Operations Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'High-Pressure Iron Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Fluid Systems Reference Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Proppant Selection Guide',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Multi-Stage Completion Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Real-Time Monitoring Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Chemical MSDS Compendium',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Frac Data Analysis Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Wellhead & BOP Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Environmental Compliance Manual',tp:'manual',s:'fracturing',sn:'Fracturing'},
    {t:'Frac Authorization & WOCS Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'High Pressure Operations Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'Fluid Disposal Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'Personnel Safety Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'Equipment Inspection Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'Environmental Impact Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'Chemical Management Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'Night Operations Policy',tp:'policy',s:'fracturing',sn:'Fracturing'},
    {t:'ALERT-FRAC-001: Iron fatigue update — mandatory NDT before Q3 campaign',tp:'alert',s:'fracturing',sn:'Fracturing'},
    {t:'ALERT-FRAC-002: Revised MAASP limits for slim-hole completions',tp:'alert',s:'fracturing',sn:'Fracturing'},
    {t:'ALERT-FRAC-003: New proppant concentration limits for high-temperature wells',tp:'alert',s:'fracturing',sn:'Fracturing'},
    {t:'ALERT-FRAC-004: Fluid additive compatibility change — check all blends',tp:'alert',s:'fracturing',sn:'Fracturing'},
    {t:'ALERT-FRAC-005: Screen-out risk in carbonate formations — updated protocol',tp:'alert',s:'fracturing',sn:'Fracturing'},
    {t:'LL-FRAC-001: Surface line failure during multi-stage frac — preventive actions',tp:'lesson',s:'fracturing',sn:'Fracturing'},
    {t:'LL-FRAC-002: Premature screen-out — root cause analysis',tp:'lesson',s:'fracturing',sn:'Fracturing'},
    {t:'LL-FRAC-003: Chemical spill during fluid mixing — improved containment',tp:'lesson',s:'fracturing',sn:'Fracturing'},
    {t:'LL-FRAC-004: Equipment failure in extreme temperature — design modifications',tp:'lesson',s:'fracturing',sn:'Fracturing'},
    {t:'LL-FRAC-005: Wellhead pressure anomaly — identification and mitigation',tp:'lesson',s:'fracturing',sn:'Fracturing'},
    {t:'LL-FRAC-006: Crew safety observation — confined space near pump unit',tp:'lesson',s:'fracturing',sn:'Fracturing'},
    {t:'LL-FRAC-007: Data acquisition failure — system improvements implemented',tp:'lesson',s:'fracturing',sn:'Fracturing'},
    {t:'FracPro RT Fracturing Simulator v10.5',tp:'software',s:'fracturing',sn:'Fracturing'},
    {t:'GOHFER Hydraulic Fracturing Software v8.2',tp:'software',s:'fracturing',sn:'Fracturing'},
    {t:'DataVan Monitoring Suite v3.0',tp:'software',s:'fracturing',sn:'Fracturing'},
    // ── Wireline ───────────────────────────────────────────────────
    {t:'WL-001 Pre-Job Hazard Assessment',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-002 Tool String Assembly SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-003 Perforation Operations SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-004 Slickline Tool Running SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-005 Memory Logging SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-006 Pump-Down Operations SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-007 Pressure Control Equipment Check',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-008 Emergency Recovery SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-009 Logging Data QC SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'WL-010 Well Re-Entry SOP',tp:'sop',s:'wireline',sn:'Wireline'},
    {t:'Wireline Operations Manual v2.8',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'Perforating Gun Systems Manual',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'PCE Maintenance Manual',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'Slickline Equipment Manual',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'Memory Tool Reference Manual',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'Data Acquisition Systems Manual',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'Shooting Panel Safety Manual',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'Wireline Vehicle Manual',tp:'manual',s:'wireline',sn:'Wireline'},
    {t:'Wireline Authorization Policy',tp:'policy',s:'wireline',sn:'Wireline'},
    {t:'Explosives Handling Policy',tp:'policy',s:'wireline',sn:'Wireline'},
    {t:'Pressure Control Policy',tp:'policy',s:'wireline',sn:'Wireline'},
    {t:'Data Security Policy',tp:'policy',s:'wireline',sn:'Wireline'},
    {t:'Personnel Certification Policy',tp:'policy',s:'wireline',sn:'Wireline'},
    {t:'LL-WL-001: Tool string stuck — successful retrieval and lessons',tp:'lesson',s:'wireline',sn:'Wireline'},
    {t:'LL-WL-002: Perforating misfire — investigation and protocol update',tp:'lesson',s:'wireline',sn:'Wireline'},
    {t:'LL-WL-003: Data loss during real-time logging — system redundancy added',tp:'lesson',s:'wireline',sn:'Wireline'},
    {t:'LL-WL-004: PCE leak detection — early intervention that prevented incident',tp:'lesson',s:'wireline',sn:'Wireline'},
    {t:'WellCAD Log Analysis Suite v5.8',tp:'software',s:'wireline',sn:'Wireline'},
    {t:'Warrior Wireline Logging System v8.4',tp:'software',s:'wireline',sn:'Wireline'},
    // ── Drilling ───────────────────────────────────────────────────
    {t:'DRL-001 Morning Safety Meeting Checklist',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-002 BHA Make-Up SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-003 Well Control Response SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-004 Casing Running SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-005 Mud Weight Adjustment SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-006 Directional Drilling SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-007 Formation Testing SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-008 Core Acquisition SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-009 Trip In/Out Procedure',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-010 Stuck Pipe Protocol',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-011 H2S Safety SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-012 Wellhead Installation SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-013 TOC Determination SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-014 Drilling Fluid Sampling SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-015 MWD Operations SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-016 LWD Operations SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-017 Bit Change SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-018 Deviation Survey SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-019 Reamer Operations SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-020 Jarring Operations SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-021 Rig Audit SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'DRL-022 End of Well Report SOP',tp:'sop',s:'drilling',sn:'Drilling'},
    {t:'Drilling Engineering Manual v5.0',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Rig Equipment Inspection Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Mud Engineering Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Directional Drilling Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Well Control Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'BOP Testing Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Casing Design Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Cementing Reference Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Formation Evaluation Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Drilling Data Management Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'HSE Critical Controls Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Tubular Inspection Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Wellsite Geology Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Rig Move Operations Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Contractor Management Manual',tp:'manual',s:'drilling',sn:'Drilling'},
    {t:'Drilling Authorization & AFE Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Well Control Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Contractor Safety Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Environmental Drilling Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Chemical Use Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Night Drilling Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Data Ownership Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Emergency Response Plan Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'BOP Testing Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Waste Management Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Crew Rotation Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'Equipment Certification Policy',tp:'policy',s:'drilling',sn:'Drilling'},
    {t:'ALERT-DRL-001: Revised kick tolerance — update all well programs',tp:'alert',s:'drilling',sn:'Drilling'},
    {t:'ALERT-DRL-002: New BOP test frequency requirements effective June 2026',tp:'alert',s:'drilling',sn:'Drilling'},
    {t:'ALERT-DRL-003: Drilling fluid compatibility issue in Zone B formations',tp:'alert',s:'drilling',sn:'Drilling'},
    {t:'ALERT-DRL-004: H2S concentration increase in Shedgum area — update PPE',tp:'alert',s:'drilling',sn:'Drilling'},
    {t:'ALERT-DRL-005: String torque limits revised — consult engineer before operations',tp:'alert',s:'drilling',sn:'Drilling'},
    {t:'ALERT-DRL-006: Casing wear report — mandated inspection before running',tp:'alert',s:'drilling',sn:'Drilling'},
    {t:'ALERT-DRL-007: New directional steering tool limitations in high-temperature wells',tp:'alert',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-001: Stuck pipe incident — lessons and preventive measures',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-002: Well control event — blowout preventer response review',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-003: Casing collapse in depleted zone — design improvement',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-004: Lost circulation management — successful remediation',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-005: Directional well tortuosity — planning improvements',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-006: Mud system failure — rapid response and redesign',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-007: Tool failure at depth — retrieval and analysis',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-008: Sidetrack planning in complex geology',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'LL-DRL-009: Wellbore instability — geomechanical study findings',tp:'lesson',s:'drilling',sn:'Drilling'},
    {t:'Well Seeker Pro Directional Software v2.6',tp:'software',s:'drilling',sn:'Drilling'},
    {t:'COMPASS Directional Planning Suite v5.1',tp:'software',s:'drilling',sn:'Drilling'},
    {t:'INTEQ Drilling Manager v4.3',tp:'software',s:'drilling',sn:'Drilling'},
    // ── Cementing ──────────────────────────────────────────────────
    {t:'CEM-001 Pre-Job Safety Check',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-002 Batch Mixing SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-003 Primary Cement Job SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-004 Displacement Procedure',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-005 Pressure Test SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-006 Float Equipment SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-007 Centralizer Placement SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-008 Remedial Squeeze SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-009 Liner Cementing SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-010 Thickening Time Test SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-011 Free Water Test SOP',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-012 Job Record Compilation',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'CEM-013 Clean-Up Procedure',tp:'sop',s:'cementing',sn:'Cementing'},
    {t:'Cementing Operations Manual v3.1',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Slurry Design Reference Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Laboratory Testing Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Float Equipment Catalog & Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Centralizer Selection Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Plug & Abandonment Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Cementing Data Analysis Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Chemical Additive Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Equipment Maintenance Manual',tp:'manual',s:'cementing',sn:'Cementing'},
    {t:'Cementing Quality Assurance Policy',tp:'policy',s:'cementing',sn:'Cementing'},
    {t:'Lab Testing Requirements Policy',tp:'policy',s:'cementing',sn:'Cementing'},
    {t:'Cement Vendor Qualification Policy',tp:'policy',s:'cementing',sn:'Cementing'},
    {t:'Environmental Policy — Cement Waste',tp:'policy',s:'cementing',sn:'Cementing'},
    {t:'Remedial Cementing Authorization Policy',tp:'policy',s:'cementing',sn:'Cementing'},
    {t:'P&A Regulatory Compliance Policy',tp:'policy',s:'cementing',sn:'Cementing'},
    {t:'Data Management Policy',tp:'policy',s:'cementing',sn:'Cementing'},
    {t:'LL-CEM-001: Cement top failure — investigation and corrective action',tp:'lesson',s:'cementing',sn:'Cementing'},
    {t:'LL-CEM-002: Free water observed after primary cement — mix design review',tp:'lesson',s:'cementing',sn:'Cementing'},
    {t:'LL-CEM-003: Failed squeeze job — lessons from over-pressuring zone',tp:'lesson',s:'cementing',sn:'Cementing'},
    {t:'LL-CEM-004: Float collar failure — pre-job testing enhancement',tp:'lesson',s:'cementing',sn:'Cementing'},
    {t:'LL-CEM-005: Centralizer placement issue in deviated well — planning improvement',tp:'lesson',s:'cementing',sn:'Cementing'},
    {t:'OptiCem Slurry Design Software v8.2',tp:'software',s:'cementing',sn:'Cementing'},
    {t:'CemCADE Cement Job Simulator v6.4',tp:'software',s:'cementing',sn:'Cementing'},
    // ── Inspection Services ────────────────────────────────────────
    {t:'INS-001 Visual Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-002 MPI Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-003 UT Wall Thickness SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-004 Pressure Test Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-005 Tubular Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-006 BOP Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-007 Valve Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-008 Crane Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-009 Lifting Equipment SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-010 Vehicle Inspection SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-011 Report Writing SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-012 Third-Party Audit SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-013 Non-Conformance Reporting',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-014 Reinspection Protocol',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'INS-015 Calibration Management SOP',tp:'sop',s:'inspection',sn:'Inspection Services'},
    {t:'NDT Methods Reference Manual',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Tubular Inspection Manual v2.4',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'BOP System Inspection Manual',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Crane & Lifting Manual',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Equipment Certification Manual',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'ASME & API Standards Reference',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Inspection Report Writing Guide',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Calibration Procedures Manual',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Rejection Criteria Manual',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Audit Trail Manual',tp:'manual',s:'inspection',sn:'Inspection Services'},
    {t:'Inspector Qualification Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Third-Party Certification Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Equipment Release Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Non-Conformance Management Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Audit Frequency Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Data Retention Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Equipment Color-Coding Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Vendor Inspection Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'Regulatory Compliance Policy',tp:'policy',s:'inspection',sn:'Inspection Services'},
    {t:'ALERT-INS-001: Updated API 5CT wall loss rejection criteria — revise all checklists',tp:'alert',s:'inspection',sn:'Inspection Services'},
    {t:'ALERT-INS-002: BOP inspection intervals reduced to 14 days in H2S zones',tp:'alert',s:'inspection',sn:'Inspection Services'},
    {t:'ALERT-INS-003: Third-party inspector qualification renewal required by August 2026',tp:'alert',s:'inspection',sn:'Inspection Services'},
    {t:'LL-INS-001: Missed crack in BOP body — enhanced inspection protocol',tp:'lesson',s:'inspection',sn:'Inspection Services'},
    {t:'LL-INS-002: Incorrect rejection call on tubulars — calibration findings',tp:'lesson',s:'inspection',sn:'Inspection Services'},
    {t:'LL-INS-003: Lifting equipment failure after passed inspection — gap analysis',tp:'lesson',s:'inspection',sn:'Inspection Services'},
    {t:'LL-INS-004: Vendor inspection discrepancy — dual verification implemented',tp:'lesson',s:'inspection',sn:'Inspection Services'},
    {t:'LL-INS-005: Crane overload incident — pre-lift checklist improvements',tp:'lesson',s:'inspection',sn:'Inspection Services'},
    {t:'LL-INS-006: NDT equipment drift — calibration frequency doubled',tp:'lesson',s:'inspection',sn:'Inspection Services'},
    {t:'InspectTrack Pro Inspection Manager v3.2',tp:'software',s:'inspection',sn:'Inspection Services'},
    {t:'NTDS Tubular Inspection Database v2.1',tp:'software',s:'inspection',sn:'Inspection Services'},
    // ── Well Safety ────────────────────────────────────────────────
    {t:'WS-001 Daily BOP Test SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-002 Kill Sheet Preparation SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-003 Well Shut-In Procedure',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-004 Hard Shut-In vs. Soft Shut-In',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-005 Stripping Operations SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-006 Bullheading SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-007 Emergency Evacuation SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-008 H2S Alarm Response SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-009 Surface Well Test SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-010 Wireline BOP Test SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-011 CT BOP Operations SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-012 IBOP SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-013 Muster & Accountability SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-014 Fire Response SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-015 Blowout Response SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-016 Barrier Verification SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-017 Well Integrity Monitoring SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-018 Casing Pressure Management',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-019 Annular Pressure Build-Up SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'WS-020 Production Test Safety SOP',tp:'sop',s:'well-safety',sn:'Well Safety'},
    {t:'Well Control Manual v6.0 (IWCF Aligned)',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'BOP Equipment Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Emergency Response Plan Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'H2S Safety Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'MAASP Calculation Guide',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Well Integrity Management Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Gas Detection Systems Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Fire & Gas System Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Barrier Management Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Evacuation & Rescue Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Competency Assessment Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'HSE Management System Manual',tp:'manual',s:'well-safety',sn:'Well Safety'},
    {t:'Well Control Authorization Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'BOP Testing Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Emergency Response Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'H2S Management Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Well Integrity Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Competency & Training Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Safety Critical Element Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Barrier Philosophy Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'HSE Case Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Simultaneous Operations (SIMOPS) Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Contractor Well Safety Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Night Operations Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Dropped Objects Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Work Permit Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'Change Management Policy',tp:'policy',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-001: CRITICAL — Revised well control kill weight calculation — mandatory briefing',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-002: BOP ram seals replacement schedule accelerated — check unit status',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-003: H2S detector calibration failure found — immediate re-calibration required',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-004: Barrier integrity concern on 3 wells — inspection ordered',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-005: New SIMOPS restriction near active completions',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-006: Updated evacuation assembly point — all rigs to update muster cards',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-007: Dropped object incident — mandatory dropped object survey',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'ALERT-WS-008: Revised kill sheet template — all drillers must recertify',tp:'alert',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-001: Gas influx during tripping — well shut-in case study',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-002: BOP function test failure — corrective actions taken',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-003: Near-miss H2S exposure — detection gap analysis',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-004: Well integrity anomaly — early detection success story',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-005: Evacuation drill findings — mustering improvements',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-006: SIMOPS incident during concurrent operations',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-007: Barrier verification failure found during well handover',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-008: Surface safety valve failure — testing protocol enhancement',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'LL-WS-009: Night-time well control event — communications lesson',tp:'lesson',s:'well-safety',sn:'Well Safety'},
    {t:'OLGA Well Control Simulator v2024.1',tp:'software',s:'well-safety',sn:'Well Safety'},
    {t:'SafetyNet BOP Management System v4.0',tp:'software',s:'well-safety',sn:'Well Safety'},
    // ── QHSE ──────────────────────────────────────────────────────
    {t:'QHSE-001 Risk Assessment (HAZID) SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-002 JSA / JHA Preparation SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-003 Permit to Work SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-004 Incident Investigation SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-005 Near-Miss Reporting SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-006 Environmental Impact Assessment',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-007 Waste Management SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-008 Chemical Management SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-009 PPE Inspection SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-010 Audit Execution SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-011 Management of Change (MOC) SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-012 Contractor HSE Evaluation',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-013 Emergency Drill Coordination SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-014 Environmental Monitoring SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-015 Quality Inspection SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE-016 Document Control SOP',tp:'sop',s:'qhse',sn:'QHSE'},
    {t:'QHSE Management System Manual v2.0',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'Risk Management Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'Environmental Management Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'Waste Disposal Reference Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'PPE Selection Guide',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'Audit Toolkit Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'Incident Investigation Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'Chemical Safety Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'OSHA/ARAMCO Alignment Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'Contractor HSE Manual',tp:'manual',s:'qhse',sn:'QHSE'},
    {t:'QHSE Policy Statement',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Zero Harm Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Environmental Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Waste Management Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Contractor HSE Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Drug & Alcohol Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Fatigue Management Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'PPE Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Management of Change Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Audit Frequency Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Incident Reporting Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Stop Work Authority Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Chemical Management Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Environmental Monitoring Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Permit to Work Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Community Relations Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Data Confidentiality Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'Quality Assurance Policy',tp:'policy',s:'qhse',sn:'QHSE'},
    {t:'ALERT-QHSE-001: New waste segregation requirements — effective immediately',tp:'alert',s:'qhse',sn:'QHSE'},
    {t:'ALERT-QHSE-002: PPE standard update — Type III gloves now required in all chemical zones',tp:'alert',s:'qhse',sn:'QHSE'},
    {t:'ALERT-QHSE-003: Contractor HSE re-qualification required Q3 2026',tp:'alert',s:'qhse',sn:'QHSE'},
    {t:'ALERT-QHSE-004: Environmental monitoring frequency doubled — spill risk area',tp:'alert',s:'qhse',sn:'QHSE'},
    {t:'LL-QHSE-001: JSA failure that led to near-miss — quality of assessment reviewed',tp:'lesson',s:'qhse',sn:'QHSE'},
    {t:'LL-QHSE-002: Environmental spill — improved bunding and response',tp:'lesson',s:'qhse',sn:'QHSE'},
    {t:'LL-QHSE-003: Contractor incident — pre-qualification gap identified',tp:'lesson',s:'qhse',sn:'QHSE'},
    {t:'LL-QHSE-004: Permit to Work violation — systemic fix applied',tp:'lesson',s:'qhse',sn:'QHSE'},
    {t:'LL-QHSE-005: Chemical exposure incident — improved storage and labeling',tp:'lesson',s:'qhse',sn:'QHSE'},
    {t:'LL-QHSE-006: MOC bypass led to equipment failure — process strengthened',tp:'lesson',s:'qhse',sn:'QHSE'},
    {t:'LL-QHSE-007: Waste classification error — training and audit response',tp:'lesson',s:'qhse',sn:'QHSE'},
    {t:'IncidentTracker Pro HSSE Suite v5.1',tp:'software',s:'qhse',sn:'QHSE'},
    {t:'HSSE Management System v3.4',tp:'software',s:'qhse',sn:'QHSE'},
    // ── Human Resources ────────────────────────────────────────────
    {t:'HR-001 Employee Onboarding SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-002 Exit & Offboarding SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-003 Performance Review SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-004 Disciplinary Procedure SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-005 Leave Application SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-006 Recruitment & Selection SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-007 Training & Development SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-008 Payroll Processing SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-009 Employee Transfer SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'HR-010 Grievance Handling SOP',tp:'sop',s:'hr',sn:'Human Resources'},
    {t:'Employee Handbook v4.0',tp:'manual',s:'hr',sn:'Human Resources'},
    {t:'HR Operations Manual',tp:'manual',s:'hr',sn:'Human Resources'},
    {t:'Compensation & Benefits Manual',tp:'manual',s:'hr',sn:'Human Resources'},
    {t:'Recruitment & Talent Acquisition Manual',tp:'manual',s:'hr',sn:'Human Resources'},
    {t:'Training & Development Manual',tp:'manual',s:'hr',sn:'Human Resources'},
    {t:'Performance Management Manual',tp:'manual',s:'hr',sn:'Human Resources'},
    {t:'HR Systems (HRMS) User Manual',tp:'manual',s:'hr',sn:'Human Resources'},
    {t:"Manager's Guide to HR Processes",tp:'manual',s:'hr',sn:'Human Resources'},
    {t:'Code of Conduct Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Equal Opportunity & Diversity Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Anti-Harassment & Anti-Bullying Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Annual & Sick Leave Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Remote & Flexible Work Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Dress Code Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Social Media & Communications Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Conflict of Interest Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Whistleblower Protection Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Employee Data Privacy Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Business Travel Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Expense Reimbursement Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Disciplinary & Termination Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Grievance & Appeals Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'Promotion & Succession Policy',tp:'policy',s:'hr',sn:'Human Resources'},
    {t:'LL-HR-001: Onboarding gaps identified through exit interview analysis — process redesigned',tp:'lesson',s:'hr',sn:'Human Resources'},
    {t:'LL-HR-002: Performance review cycle delay — revised timeline and manager training',tp:'lesson',s:'hr',sn:'Human Resources'},
    {t:'LL-HR-003: Recruitment timeline reduction — structured interview process adopted',tp:'lesson',s:'hr',sn:'Human Resources'},
    {t:'LL-HR-004: Policy communication failure — multi-channel distribution approach adopted',tp:'lesson',s:'hr',sn:'Human Resources'},
    {t:'LL-HR-005: HRMS data accuracy issues — validation controls implemented',tp:'lesson',s:'hr',sn:'Human Resources'},
    {t:'Oracle HRMS Integration Pack v12.2',tp:'software',s:'hr',sn:'Human Resources'},
    // ── TWS Maintenance ────────────────────────────────────────────
    {t:'TWS-001 PM Schedule Execution SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-002 Corrective Maintenance SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-003 Calibration SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-004 Tool Pre-Job Inspection SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-005 Tool Post-Job Inspection SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-006 Pressure Gauge Certification SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-007 Motor Overhaul SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-008 Hydraulic System Maintenance SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-009 Electrical Inspection SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-010 Valve Overhaul SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-011 Workshop Safety SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-012 Tool Storage SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-013 Out-of-Service Equipment SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'TWS-014 Return-to-Service Approval SOP',tp:'sop',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Preventive Maintenance Manual v2.1',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Workshop Operations Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Hydraulic Systems Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Electrical Maintenance Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Calibration Standards Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Tool Inspection Criteria Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Crane & Rigging Maintenance Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Motor & Pump Overhaul Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Pressure Equipment Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Workshop Equipment Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'CMMS User Manual',tp:'manual',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Maintenance Authorization Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Calibration Frequency Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Out-of-Service Equipment Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Workshop Safety Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Third-Party Repair Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Spare Parts Management Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Tool Identification & Tagging Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'Return-to-Service Policy',tp:'policy',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'LL-TWS-001: In-field tool failure — PM gap identified and corrected',tp:'lesson',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'LL-TWS-002: Calibration drift not caught — revised frequency policy',tp:'lesson',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'LL-TWS-003: Hydraulic seal failure — new inspection criteria added',tp:'lesson',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'LL-TWS-004: Incorrect reassembly after overhaul — checklist improvement',tp:'lesson',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'LL-TWS-005: Motor bearing failure — vibration monitoring added',tp:'lesson',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'LL-TWS-006: Spare parts stockout — inventory management improvement',tp:'lesson',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'SAP PM Integration Toolkit v7.4',tp:'software',s:'tws-maintenance',sn:'TWS Maintenance'},
    {t:'AssetTrak Maintenance Manager v3.2',tp:'software',s:'tws-maintenance',sn:'TWS Maintenance'},
    // ── Well Testing ───────────────────────────────────────────────
    {t:'WT-001 Pre-Test Safety Checklist',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-002 Surface Testing Equipment Rig-Up SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-003 DST Operations SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-004 Pressure Buildup Test SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-005 Multi-Rate Flow Test SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-006 Well Cleanup SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-007 Separator Operations SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-008 Emergency Shutdown SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-009 Data Acquisition SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'WT-010 Post-Test Reporting SOP',tp:'sop',s:'well-testing',sn:'Well Testing'},
    {t:'Well Testing Operations Manual v3.0',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'Surface Testing Equipment Manual',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'Separator & Wellhead Tester Manual',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'Pressure Gauge Calibration Manual',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'DST Tool Assembly Manual',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'Gas Chromatograph Operations Manual',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'Flowback & Clean-Up Manual',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'Well Test Data Analysis Manual',tp:'manual',s:'well-testing',sn:'Well Testing'},
    {t:'Well Testing Authorization Policy',tp:'policy',s:'well-testing',sn:'Well Testing'},
    {t:'Surface Testing Equipment Policy',tp:'policy',s:'well-testing',sn:'Well Testing'},
    {t:'H2S Management Policy for Well Tests',tp:'policy',s:'well-testing',sn:'Well Testing'},
    {t:'Data Ownership & Confidentiality Policy',tp:'policy',s:'well-testing',sn:'Well Testing'},
    {t:'Third-Party Equipment Policy',tp:'policy',s:'well-testing',sn:'Well Testing'},
    {t:'Environmental Compliance — Well Testing',tp:'policy',s:'well-testing',sn:'Well Testing'},
    {t:'ALERT-WT-001: H2S risk elevation in Unayzah formation — mandatory briefing before all tests',tp:'alert',s:'well-testing',sn:'Well Testing'},
    {t:'ALERT-WT-002: Separator pressure rating update — verify all units before deployment',tp:'alert',s:'well-testing',sn:'Well Testing'},
    {t:'LL-WT-001: Well test data loss due to gauge failure — redundancy protocol added',tp:'lesson',s:'well-testing',sn:'Well Testing'},
    {t:'LL-WT-002: Unexpected H2S during DST — emergency response review',tp:'lesson',s:'well-testing',sn:'Well Testing'},
    {t:'LL-WT-003: Separator overflow incident — improved monitoring implemented',tp:'lesson',s:'well-testing',sn:'Well Testing'},
    {t:'LL-WT-004: Flow rate measurement discrepancy — calibration procedure improved',tp:'lesson',s:'well-testing',sn:'Well Testing'},
    {t:'Saphir Well Test Analysis Software v5.0',tp:'software',s:'well-testing',sn:'Well Testing'},
    {t:'OFM Well & Reservoir Analysis v2019.1',tp:'software',s:'well-testing',sn:'Well Testing'},
  ];
  return S;
})();
