// Shared segment data — loaded by dashboard.html
const TAQA_SEGMENTS = {
  'coiled-tubing': {
    name:'Coiled Tubing', icon:'🔄', tag:'Operations',
    desc:'Coiled tubing operations, equipment specifications, and continuous operation field procedures for all CT units.',
    sops:12, manuals:9, policies:6, alerts:3, lessons:5, software:3,
    docs:{
      sops:['CT-001 Pre-Job Safety Checklist','CT-002 BHA Assembly Procedure','CT-003 Well Entry Protocol',
        'CT-004 Emergency Disconnect Procedure','CT-005 Pressure Testing Procedure','CT-006 CT Unit Rig-Up & Rig-Down',
        'CT-007 Nitrogen Injection SOP','CT-008 Milling Operations SOP','CT-009 Acid Stimulation SOP',
        'CT-010 Fishing Operations SOP','CT-011 Logging While CT SOP','CT-012 Post-Job Reporting SOP'],
      manuals:['CT Unit Maintenance Manual v3.2','BHA Component Reference Manual','Injector Head Operations Manual',
        'Control Cabin Systems Manual','CT String Inspection Manual','Crane & Rigging Safety Manual',
        'Chemical Handling Manual','Data Acquisition Manual','CT Wellhead Equipment Manual'],
      policies:['CT Operations Authorization Policy','Equipment Certification Policy','Crew Competency Requirements',
        'Environmental Compliance Policy','CT Asset Management Policy','Incident Reporting Policy'],
      alerts:['ALERT-CT-001: BHA connector fatigue — inspect all units before next run',
        'ALERT-CT-002: New pressure rating for 2-inch CT string — effective immediately',
        'ALERT-CT-003: Chemical compatibility update for H2S environments'],
      lessons:['LL-CT-001: Near-miss during CT rig-up — lessons from H2 field',
        'LL-CT-002: CT string failure analysis — root cause and prevention',
        'LL-CT-003: Lessons from coiled tubing fishing operation',
        'LL-CT-004: Mud motor stall — diagnosis and recovery',
        'LL-CT-005: Pressure integrity test failure — field findings'],
      software:['Orion CT Control System | v2.3','WellPlan CT Simulator | v4.1','CoilScan Inspection Reporter | v1.8']
    }
  },
  'fracturing': {
    name:'Fracturing', icon:'💥', tag:'Stimulation',
    desc:'Hydraulic fracturing design, execution procedures, fluid systems, pump operations, and post-job analysis documentation.',
    sops:18, manuals:11, policies:8, alerts:5, lessons:7, software:3,
    docs:{
      sops:['FRAC-001 Pre-Job Safety Meeting','FRAC-002 Pump Rig-Up Procedure','FRAC-003 Iron Pressure Test',
        'FRAC-004 Fluid Mixing SOP','FRAC-005 Proppant Handling SOP','FRAC-006 Treatment Execution SOP',
        'FRAC-007 Emergency Shutdown Procedure','FRAC-008 Post-Job Flowback SOP','FRAC-009 Multi-Stage Frac SOP',
        'FRAC-010 Acid Pre-Flush SOP','FRAC-011 Chemical Additive SOP','FRAC-012 Wellhead Connection SOP',
        'FRAC-013 Data Van Operations SOP','FRAC-014 Blender Operations SOP','FRAC-015 Iron Inspection SOP',
        'FRAC-016 Night Operations SOP','FRAC-017 Screen-Out Response SOP','FRAC-018 Post-Job Cleanup SOP'],
      manuals:['Hydraulic Fracturing Design Manual v4.1','Pump Unit Operations Manual','High-Pressure Iron Manual',
        'Fluid Systems Reference Manual','Proppant Selection Guide','Multi-Stage Completion Manual',
        'Real-Time Monitoring Manual','Chemical MSDS Compendium','Frac Data Analysis Manual',
        'Wellhead & BOP Manual','Environmental Compliance Manual'],
      policies:['Frac Authorization & WOCS Policy','High Pressure Operations Policy','Fluid Disposal Policy',
        'Personnel Safety Policy','Equipment Inspection Policy','Environmental Impact Policy',
        'Chemical Management Policy','Night Operations Policy'],
      alerts:['ALERT-FRAC-001: Iron fatigue update — mandatory NDT before Q3 campaign',
        'ALERT-FRAC-002: Revised MAASP limits for slim-hole completions',
        'ALERT-FRAC-003: New proppant concentration limits for high-temperature wells',
        'ALERT-FRAC-004: Fluid additive compatibility change — check all blends',
        'ALERT-FRAC-005: Screen-out risk in carbonate formations — updated protocol'],
      lessons:['LL-FRAC-001: Surface line failure during multi-stage frac — preventive actions',
        'LL-FRAC-002: Premature screen-out — root cause analysis',
        'LL-FRAC-003: Chemical spill during fluid mixing — improved containment',
        'LL-FRAC-004: Equipment failure in extreme temperature — design modifications',
        'LL-FRAC-005: Wellhead pressure anomaly — identification and mitigation',
        'LL-FRAC-006: Crew safety observation — confined space near pump unit',
        'LL-FRAC-007: Data acquisition failure — system improvements implemented'],
      software:['FracPro RT Fracturing Simulator | v10.5','GOHFER Hydraulic Fracturing Software | v8.2','DataVan Monitoring Suite | v3.0']
    }
  },
  'wireline': {
    name:'Wireline', icon:'📡', tag:'Logging',
    desc:'Wireline logging, perforating, and well intervention operations — memory, pump-down, and slickline procedures.',
    sops:10, manuals:8, policies:5, alerts:0, lessons:4, software:2,
    docs:{
      sops:['WL-001 Pre-Job Hazard Assessment','WL-002 Tool String Assembly SOP','WL-003 Perforation Operations SOP',
        'WL-004 Slickline Tool Running SOP','WL-005 Memory Logging SOP','WL-006 Pump-Down Operations SOP',
        'WL-007 Pressure Control Equipment Check','WL-008 Emergency Recovery SOP','WL-009 Logging Data QC SOP','WL-010 Well Re-Entry SOP'],
      manuals:['Wireline Operations Manual v2.8','Perforating Gun Systems Manual','PCE Maintenance Manual',
        'Slickline Equipment Manual','Memory Tool Reference Manual','Data Acquisition Systems Manual',
        'Shooting Panel Safety Manual','Wireline Vehicle Manual'],
      policies:['Wireline Authorization Policy','Explosives Handling Policy','Pressure Control Policy',
        'Data Security Policy','Personnel Certification Policy'],
      alerts:[],
      lessons:['LL-WL-001: Tool string stuck — successful retrieval and lessons',
        'LL-WL-002: Perforating misfire — investigation and protocol update',
        'LL-WL-003: Data loss during real-time logging — system redundancy added',
        'LL-WL-004: PCE leak detection — early intervention that prevented incident'],
      software:['WellCAD Log Analysis Suite | v5.8','Warrior Wireline Logging System | v8.4']
    }
  },
  'drilling': {
    name:'Drilling', icon:'⛏️', tag:'Drilling Ops',
    desc:'Drilling engineering, well planning, rig operations, mud systems, BHA design, and formation evaluation procedures.',
    sops:22, manuals:15, policies:12, alerts:7, lessons:9, software:3,
    docs:{
      sops:['DRL-001 Morning Safety Meeting Checklist','DRL-002 BHA Make-Up SOP','DRL-003 Well Control Response SOP',
        'DRL-004 Casing Running SOP','DRL-005 Mud Weight Adjustment SOP','DRL-006 Directional Drilling SOP',
        'DRL-007 Formation Testing SOP','DRL-008 Core Acquisition SOP','DRL-009 Trip In/Out Procedure',
        'DRL-010 Stuck Pipe Protocol','DRL-011 H2S Safety SOP','DRL-012 Wellhead Installation SOP',
        'DRL-013 TOC Determination SOP','DRL-014 Drilling Fluid Sampling SOP','DRL-015 MWD Operations SOP',
        'DRL-016 LWD Operations SOP','DRL-017 Bit Change SOP','DRL-018 Deviation Survey SOP',
        'DRL-019 Reamer Operations SOP','DRL-020 Jarring Operations SOP','DRL-021 Rig Audit SOP','DRL-022 End of Well Report SOP'],
      manuals:['Drilling Engineering Manual v5.0','Rig Equipment Inspection Manual','Mud Engineering Manual',
        'Directional Drilling Manual','Well Control Manual','BOP Testing Manual','Casing Design Manual',
        'Cementing Reference Manual','Formation Evaluation Manual','Drilling Data Management Manual',
        'HSE Critical Controls Manual','Tubular Inspection Manual','Wellsite Geology Manual',
        'Rig Move Operations Manual','Contractor Management Manual'],
      policies:['Drilling Authorization & AFE Policy','Well Control Policy','Contractor Safety Policy',
        'Environmental Drilling Policy','Chemical Use Policy','Night Drilling Policy',
        'Data Ownership Policy','Emergency Response Plan Policy','BOP Testing Policy',
        'Waste Management Policy','Crew Rotation Policy','Equipment Certification Policy'],
      alerts:['ALERT-DRL-001: Revised kick tolerance — update all well programs',
        'ALERT-DRL-002: New BOP test frequency requirements effective June 2026',
        'ALERT-DRL-003: Drilling fluid compatibility issue in Zone B formations',
        'ALERT-DRL-004: H2S concentration increase in Shedgum area — update PPE',
        'ALERT-DRL-005: String torque limits revised — consult engineer before operations',
        'ALERT-DRL-006: Casing wear report — mandated inspection before running',
        'ALERT-DRL-007: New directional steering tool limitations in high-temperature wells'],
      lessons:['LL-DRL-001: Stuck pipe incident — lessons and preventive measures',
        'LL-DRL-002: Well control event — blowout preventer response review',
        'LL-DRL-003: Casing collapse in depleted zone — design improvement',
        'LL-DRL-004: Lost circulation management — successful remediation',
        'LL-DRL-005: Directional well tortuosity — planning improvements',
        'LL-DRL-006: Mud system failure — rapid response and redesign',
        'LL-DRL-007: Tool failure at depth — retrieval and analysis',
        'LL-DRL-008: Sidetrack planning in complex geology',
        'LL-DRL-009: Wellbore instability — geomechanical study findings'],
      software:['Well Seeker Pro Directional Software | v2.6','COMPASS Directional Planning Suite | v5.1','INTEQ Drilling Manager | v4.3']
    }
  },
  'cementing': {
    name:'Cementing', icon:'🏗️', tag:'Well Construction',
    desc:'Primary and remedial cementing operations, slurry design, quality control standards, and pressure testing procedures.',
    sops:13, manuals:9, policies:7, alerts:0, lessons:5, software:2,
    docs:{
      sops:['CEM-001 Pre-Job Safety Check','CEM-002 Batch Mixing SOP','CEM-003 Primary Cement Job SOP',
        'CEM-004 Displacement Procedure','CEM-005 Pressure Test SOP','CEM-006 Float Equipment SOP',
        'CEM-007 Centralizer Placement SOP','CEM-008 Remedial Squeeze SOP','CEM-009 Liner Cementing SOP',
        'CEM-010 Thickening Time Test SOP','CEM-011 Free Water Test SOP','CEM-012 Job Record Compilation','CEM-013 Clean-Up Procedure'],
      manuals:['Cementing Operations Manual v3.1','Slurry Design Reference Manual','Laboratory Testing Manual',
        'Float Equipment Catalog & Manual','Centralizer Selection Manual','Plug & Abandonment Manual',
        'Cementing Data Analysis Manual','Chemical Additive Manual','Equipment Maintenance Manual'],
      policies:['Cementing Quality Assurance Policy','Lab Testing Requirements Policy','Cement Vendor Qualification Policy',
        'Environmental Policy — Cement Waste','Remedial Cementing Authorization Policy',
        'P&A Regulatory Compliance Policy','Data Management Policy'],
      alerts:[],
      lessons:['LL-CEM-001: Cement top failure — investigation and corrective action',
        'LL-CEM-002: Free water observed after primary cement — mix design review',
        'LL-CEM-003: Failed squeeze job — lessons from over-pressuring zone',
        'LL-CEM-004: Float collar failure — pre-job testing enhancement',
        'LL-CEM-005: Centralizer placement issue in deviated well — planning improvement'],
      software:['OptiCem Slurry Design Software | v8.2','CemCADE Cement Job Simulator | v6.4']
    }
  },
  'inspection': {
    name:'Inspection Services', icon:'🔍', tag:'Compliance',
    desc:'Equipment inspection standards, NDT methods, compliance requirements, certification workflows, and audit documentation.',
    sops:15, manuals:10, policies:9, alerts:3, lessons:6, software:2,
    docs:{
      sops:['INS-001 Visual Inspection SOP','INS-002 MPI Inspection SOP','INS-003 UT Wall Thickness SOP',
        'INS-004 Pressure Test Inspection SOP','INS-005 Tubular Inspection SOP','INS-006 BOP Inspection SOP',
        'INS-007 Valve Inspection SOP','INS-008 Crane Inspection SOP','INS-009 Lifting Equipment SOP',
        'INS-010 Vehicle Inspection SOP','INS-011 Report Writing SOP','INS-012 Third-Party Audit SOP',
        'INS-013 Non-Conformance Reporting','INS-014 Reinspection Protocol','INS-015 Calibration Management SOP'],
      manuals:['NDT Methods Reference Manual','Tubular Inspection Manual v2.4','BOP System Inspection Manual',
        'Crane & Lifting Manual','Equipment Certification Manual','ASME & API Standards Reference',
        'Inspection Report Writing Guide','Calibration Procedures Manual','Rejection Criteria Manual','Audit Trail Manual'],
      policies:['Inspector Qualification Policy','Third-Party Certification Policy','Equipment Release Policy',
        'Non-Conformance Management Policy','Audit Frequency Policy','Data Retention Policy',
        'Equipment Color-Coding Policy','Vendor Inspection Policy','Regulatory Compliance Policy'],
      alerts:['ALERT-INS-001: Updated API 5CT wall loss rejection criteria — revise all checklists',
        'ALERT-INS-002: BOP inspection intervals reduced to 14 days in H2S zones',
        'ALERT-INS-003: Third-party inspector qualification renewal required by August 2026'],
      lessons:['LL-INS-001: Missed crack in BOP body — enhanced inspection protocol',
        'LL-INS-002: Incorrect rejection call on tubulars — calibration findings',
        'LL-INS-003: Lifting equipment failure after passed inspection — gap analysis',
        'LL-INS-004: Vendor inspection discrepancy — dual verification implemented',
        'LL-INS-005: Crane overload incident — pre-lift checklist improvements',
        'LL-INS-006: NDT equipment drift — calibration frequency doubled'],
      software:['InspectTrack Pro Inspection Manager | v3.2','NTDS Tubular Inspection Database | v2.1']
    }
  },
  'well-safety': {
    name:'Well Safety', icon:'🛡️', tag:'Safety Critical',
    desc:'Well control procedures, blowout prevention, emergency response plans, pressure management, and safety management systems.',
    sops:20, manuals:12, policies:15, alerts:8, lessons:9, software:2,
    docs:{
      sops:['WS-001 Daily BOP Test SOP','WS-002 Kill Sheet Preparation SOP','WS-003 Well Shut-In Procedure',
        'WS-004 Hard Shut-In vs. Soft Shut-In','WS-005 Stripping Operations SOP','WS-006 Bullheading SOP',
        'WS-007 Emergency Evacuation SOP','WS-008 H2S Alarm Response SOP','WS-009 Surface Well Test SOP',
        'WS-010 Wireline BOP Test SOP','WS-011 CT BOP Operations SOP','WS-012 IBOP SOP',
        'WS-013 Muster & Accountability SOP','WS-014 Fire Response SOP','WS-015 Blowout Response SOP',
        'WS-016 Barrier Verification SOP','WS-017 Well Integrity Monitoring SOP','WS-018 Casing Pressure Management',
        'WS-019 Annular Pressure Build-Up SOP','WS-020 Production Test Safety SOP'],
      manuals:['Well Control Manual v6.0 (IWCF Aligned)','BOP Equipment Manual','Emergency Response Plan Manual',
        'H2S Safety Manual','MAASP Calculation Guide','Well Integrity Management Manual',
        'Gas Detection Systems Manual','Fire & Gas System Manual','Barrier Management Manual',
        'Evacuation & Rescue Manual','Competency Assessment Manual','HSE Management System Manual'],
      policies:['Well Control Authorization Policy','BOP Testing Policy','Emergency Response Policy',
        'H2S Management Policy','Well Integrity Policy','Competency & Training Policy',
        'Safety Critical Element Policy','Barrier Philosophy Policy','HSE Case Policy',
        'Simultaneous Operations (SIMOPS) Policy','Contractor Well Safety Policy','Night Operations Policy',
        'Dropped Objects Policy','Work Permit Policy','Change Management Policy'],
      alerts:['ALERT-WS-001: CRITICAL — Revised well control kill weight calculation — mandatory briefing',
        'ALERT-WS-002: BOP ram seals replacement schedule accelerated — check unit status',
        'ALERT-WS-003: H2S detector calibration failure found — immediate re-calibration required',
        'ALERT-WS-004: Barrier integrity concern on 3 wells — inspection ordered',
        'ALERT-WS-005: New SIMOPS restriction near active completions',
        'ALERT-WS-006: Updated evacuation assembly point — all rigs to update muster cards',
        'ALERT-WS-007: Dropped object incident — mandatory dropped object survey',
        'ALERT-WS-008: Revised kill sheet template — all drillers must recertify'],
      lessons:['LL-WS-001: Gas influx during tripping — well shut-in case study',
        'LL-WS-002: BOP function test failure — corrective actions taken',
        'LL-WS-003: Near-miss H2S exposure — detection gap analysis',
        'LL-WS-004: Well integrity anomaly — early detection success story',
        'LL-WS-005: Evacuation drill findings — mustering improvements',
        'LL-WS-006: SIMOPS incident during concurrent operations',
        'LL-WS-007: Barrier verification failure found during well handover',
        'LL-WS-008: Surface safety valve failure — testing protocol enhancement',
        'LL-WS-009: Night-time well control event — communications lesson'],
      software:['OLGA Well Control Simulator | v2024.1','SafetyNet BOP Management System | v4.0']
    }
  },
  'qhse': {
    name:'QHSE', icon:'✅', tag:'Quality & Safety',
    desc:'Quality, Health, Safety and Environmental management standards, risk assessment, compliance, and audit documentation.',
    sops:16, manuals:10, policies:18, alerts:4, lessons:7, software:2,
    docs:{
      sops:['QHSE-001 Risk Assessment (HAZID) SOP','QHSE-002 JSA / JHA Preparation SOP','QHSE-003 Permit to Work SOP',
        'QHSE-004 Incident Investigation SOP','QHSE-005 Near-Miss Reporting SOP','QHSE-006 Environmental Impact Assessment',
        'QHSE-007 Waste Management SOP','QHSE-008 Chemical Management SOP','QHSE-009 PPE Inspection SOP',
        'QHSE-010 Audit Execution SOP','QHSE-011 Management of Change (MOC) SOP','QHSE-012 Contractor HSE Evaluation',
        'QHSE-013 Emergency Drill Coordination SOP','QHSE-014 Environmental Monitoring SOP',
        'QHSE-015 Quality Inspection SOP','QHSE-016 Document Control SOP'],
      manuals:['QHSE Management System Manual v2.0','Risk Management Manual','Environmental Management Manual',
        'Waste Disposal Reference Manual','PPE Selection Guide','Audit Toolkit Manual',
        'Incident Investigation Manual','Chemical Safety Manual','OSHA/ARAMCO Alignment Manual','Contractor HSE Manual'],
      policies:['QHSE Policy Statement','Zero Harm Policy','Environmental Policy','Waste Management Policy',
        'Contractor HSE Policy','Drug & Alcohol Policy','Fatigue Management Policy','PPE Policy',
        'Management of Change Policy','Audit Frequency Policy','Incident Reporting Policy',
        'Stop Work Authority Policy','Chemical Management Policy','Environmental Monitoring Policy',
        'Permit to Work Policy','Community Relations Policy','Data Confidentiality Policy','Quality Assurance Policy'],
      alerts:['ALERT-QHSE-001: New waste segregation requirements — effective immediately',
        'ALERT-QHSE-002: PPE standard update — Type III gloves now required in all chemical zones',
        'ALERT-QHSE-003: Contractor HSE re-qualification required Q3 2026',
        'ALERT-QHSE-004: Environmental monitoring frequency doubled — spill risk area'],
      lessons:['LL-QHSE-001: JSA failure that led to near-miss — quality of assessment reviewed',
        'LL-QHSE-002: Environmental spill — improved bunding and response',
        'LL-QHSE-003: Contractor incident — pre-qualification gap identified',
        'LL-QHSE-004: Permit to Work violation — systemic fix applied',
        'LL-QHSE-005: Chemical exposure incident — improved storage and labeling',
        'LL-QHSE-006: MOC bypass led to equipment failure — process strengthened',
        'LL-QHSE-007: Waste classification error — training and audit response'],
      software:['IncidentTracker Pro HSSE Suite | v5.1','HSSE Management System v3.4']
    }
  },
  'hr': {
    name:'Human Resources', icon:'👥', tag:'HR & People',
    desc:'TAQA HR policies, employee standards, code of conduct, organizational guidelines, and personnel procedures for all employees.',
    sops:10, manuals:8, policies:15, alerts:0, lessons:5, software:1,
    docs:{
      sops:['HR-001 Employee Onboarding SOP','HR-002 Exit & Offboarding SOP','HR-003 Performance Review SOP',
        'HR-004 Disciplinary Procedure SOP','HR-005 Leave Application SOP','HR-006 Recruitment & Selection SOP',
        'HR-007 Training & Development SOP','HR-008 Payroll Processing SOP','HR-009 Employee Transfer SOP',
        'HR-010 Grievance Handling SOP'],
      manuals:['Employee Handbook v4.0','HR Operations Manual','Compensation & Benefits Manual',
        'Recruitment & Talent Acquisition Manual','Training & Development Manual',
        'Performance Management Manual','HR Systems (HRMS) User Manual','Manager\'s Guide to HR Processes'],
      policies:['Code of Conduct Policy','Equal Opportunity & Diversity Policy','Anti-Harassment & Anti-Bullying Policy',
        'Annual & Sick Leave Policy','Remote & Flexible Work Policy','Dress Code Policy',
        'Social Media & Communications Policy','Conflict of Interest Policy','Whistleblower Protection Policy',
        'Employee Data Privacy Policy','Business Travel Policy','Expense Reimbursement Policy',
        'Disciplinary & Termination Policy','Grievance & Appeals Policy','Promotion & Succession Policy'],
      alerts:[],
      lessons:['LL-HR-001: Onboarding gaps identified through exit interview analysis — process redesigned',
        'LL-HR-002: Performance review cycle delay — revised timeline and manager training',
        'LL-HR-003: Recruitment timeline reduction — structured interview process adopted',
        'LL-HR-004: Policy communication failure — multi-channel distribution approach adopted',
        'LL-HR-005: HRMS data accuracy issues — validation controls implemented'],
      software:['Oracle HRMS Integration Pack | v12.2']
    }
  },
  'tws-maintenance': {
    name:'TWS Maintenance', icon:'🔧', tag:'Maintenance',
    desc:'Tool and equipment maintenance schedules, preventive maintenance programs, repair procedures, calibration, and technical specs.',
    sops:14, manuals:11, policies:8, alerts:0, lessons:6, software:2,
    docs:{
      sops:['TWS-001 PM Schedule Execution SOP','TWS-002 Corrective Maintenance SOP','TWS-003 Calibration SOP',
        'TWS-004 Tool Pre-Job Inspection SOP','TWS-005 Tool Post-Job Inspection SOP','TWS-006 Pressure Gauge Certification SOP',
        'TWS-007 Motor Overhaul SOP','TWS-008 Hydraulic System Maintenance SOP','TWS-009 Electrical Inspection SOP',
        'TWS-010 Valve Overhaul SOP','TWS-011 Workshop Safety SOP','TWS-012 Tool Storage SOP',
        'TWS-013 Out-of-Service Equipment SOP','TWS-014 Return-to-Service Approval SOP'],
      manuals:['Preventive Maintenance Manual v2.1','Workshop Operations Manual','Hydraulic Systems Manual',
        'Electrical Maintenance Manual','Calibration Standards Manual','Tool Inspection Criteria Manual',
        'Crane & Rigging Maintenance Manual','Motor & Pump Overhaul Manual','Pressure Equipment Manual',
        'Workshop Equipment Manual','CMMS User Manual'],
      policies:['Maintenance Authorization Policy','Calibration Frequency Policy','Out-of-Service Equipment Policy',
        'Workshop Safety Policy','Third-Party Repair Policy','Spare Parts Management Policy',
        'Tool Identification & Tagging Policy','Return-to-Service Policy'],
      alerts:[],
      lessons:['LL-TWS-001: In-field tool failure — PM gap identified and corrected',
        'LL-TWS-002: Calibration drift not caught — revised frequency policy',
        'LL-TWS-003: Hydraulic seal failure — new inspection criteria added',
        'LL-TWS-004: Incorrect reassembly after overhaul — checklist improvement',
        'LL-TWS-005: Motor bearing failure — vibration monitoring added',
        'LL-TWS-006: Spare parts stockout — inventory management improvement'],
      software:['SAP PM Integration Toolkit | v7.4','AssetTrak Maintenance Manager | v3.2']
    }
  },
  'well-testing': {
    name:'Well Testing', icon:'🧪', tag:'Production Testing',
    desc:'Well test design, pressure buildup analysis, surface testing equipment operations, multi-rate flow testing, and production optimization procedures.',
    sops:10, manuals:8, policies:6, alerts:2, lessons:4, software:2,
    docs:{
      sops:['WT-001 Pre-Test Safety Checklist','WT-002 Surface Testing Equipment Rig-Up SOP',
        'WT-003 DST Operations SOP','WT-004 Pressure Buildup Test SOP',
        'WT-005 Multi-Rate Flow Test SOP','WT-006 Well Cleanup SOP',
        'WT-007 Separator Operations SOP','WT-008 Emergency Shutdown SOP',
        'WT-009 Data Acquisition SOP','WT-010 Post-Test Reporting SOP'],
      manuals:['Well Testing Operations Manual v3.0','Surface Testing Equipment Manual',
        'Separator & Wellhead Tester Manual','Pressure Gauge Calibration Manual',
        'DST Tool Assembly Manual','Gas Chromatograph Operations Manual',
        'Flowback & Clean-Up Manual','Well Test Data Analysis Manual'],
      policies:['Well Testing Authorization Policy','Surface Testing Equipment Policy',
        'H2S Management Policy for Well Tests','Data Ownership & Confidentiality Policy',
        'Third-Party Equipment Policy','Environmental Compliance — Well Testing'],
      alerts:['ALERT-WT-001: H2S risk elevation in Unayzah formation — mandatory briefing before all tests',
        'ALERT-WT-002: Separator pressure rating update — verify all units before deployment'],
      lessons:['LL-WT-001: Well test data loss due to gauge failure — redundancy protocol added',
        'LL-WT-002: Unexpected H2S during DST — emergency response review',
        'LL-WT-003: Separator overflow incident — improved monitoring implemented',
        'LL-WT-004: Flow rate measurement discrepancy — calibration procedure improved'],
      software:['Saphir Well Test Analysis Software | v5.0','OFM Well & Reservoir Analysis | v2019.1']
    }
  },
  'cybersecurity': {
    name:'Cybersecurity', icon:'🔐', tag:'IT & Security',
    desc:'Cybersecurity governance, policies, standards, operational procedures, security awareness programs, and compliance documentation for TAQA\'s IT and OT environments.',
    sops:10, manuals:8, policies:12, alerts:5, lessons:6, software:2,
    tabLabels:{sops:'Procedures', manuals:'Standards', policies:'Policies', alerts:'Compliance', lessons:'Awareness'},
    contributors:[{name:'Mohammed Al Obaid', role:'Cybersecurity Director'},{name:'Afnan Al Khabty', role:'Senior Cyber Security Analyst'}],
    docs:{
      sops:['CS-PROC-001 Incident Response Procedure','CS-PROC-002 Access Control Request Procedure',
        'CS-PROC-003 Vulnerability Assessment Procedure','CS-PROC-004 Security Patch Management Procedure',
        'CS-PROC-005 Data Backup & Recovery Procedure','CS-PROC-006 Privileged Account Management Procedure',
        'CS-PROC-007 Security Monitoring & Logging Procedure','CS-PROC-008 Third-Party Access Procedure',
        'CS-PROC-009 Penetration Testing Procedure','CS-PROC-010 Security Change Management Procedure'],
      manuals:['TAQA Cybersecurity Framework Standard v2.0','Network Security Standard',
        'Identity & Access Management Standard','Endpoint Security Standard',
        'Cloud Security Standard','OT/ICS Security Standard',
        'Data Classification & Handling Standard','Encryption & Key Management Standard'],
      policies:['Information Security Policy','Acceptable Use Policy','Password & Authentication Policy',
        'Data Privacy & Protection Policy','Email & Communication Security Policy',
        'Remote Work & VPN Policy','Third-Party Vendor Security Policy',
        'Bring Your Own Device (BYOD) Policy','Physical Security Policy',
        'Cyber Incident Response Policy','Business Continuity & Disaster Recovery Policy',
        'Software Licensing & Asset Management Policy'],
      alerts:['COMP-001: Annual security awareness training due — all staff must complete by July 2026',
        'COMP-002: ISO 27001 internal audit scheduled — prepare evidence packages',
        'COMP-003: NCA CSCC compliance review Q3 2026 — assess current posture',
        'COMP-004: Third-party vendor security assessments due — 12 vendors pending',
        'COMP-005: PDPL (Data Protection Law) compliance deadline — review data handling processes'],
      lessons:['AWR-001: Phishing simulation results — 18% click rate identified, targeted training deployed',
        'AWR-002: Social engineering awareness — lessons from simulated vishing campaign',
        'AWR-003: USB drop test findings — physical security awareness gap addressed',
        'AWR-004: Password hygiene campaign — results from enterprise-wide audit',
        'AWR-005: Ransomware tabletop exercise — incident response gaps identified',
        'AWR-006: Insider threat awareness — case study and preventive controls'],
      software:['Microsoft Defender for Endpoint | v4.18','CyberArk Privileged Access Manager | v13.0']
    },
    docRevisions: {
      'CS-PROC-001 Incident Response Procedure': {
        current: 4,
        history: [
          { rev:4, date:'May 2026',  author:'Mohammed Al Obaid',  note:'Strengthened escalation workflow; added direct communication protocol with Saudi CERT and mandatory 2-hour containment deadline for Critical (P1) incidents.' },
          { rev:3, date:'Jan 2026',  author:'Afnan Al Khabty',    note:'Integrated NCA Essential Cybersecurity Controls v2.0 requirements; added OT/ICS environment-specific response steps.' },
          { rev:2, date:'Aug 2025',  author:'Mohammed Al Obaid',  note:'Updated incident classification matrix (P1–P4); revised external notification thresholds and CIRT activation criteria.' },
          { rev:1, date:'Mar 2025',  author:'Afnan Al Khabty',    note:'Initial release — baseline incident response procedure aligned with ISO/IEC 27035 and NIST SP 800-61.' }
        ]
      },
      'TAQA Cybersecurity Framework Standard v2.0': {
        current: 2,
        history: [
          { rev:2, date:'Apr 2026',  author:'Mohammed Al Obaid',  note:'Added OT/ICS security controls section; aligned with NERC CIP standards and NCA Operational Technology security guidelines.' },
          { rev:1, date:'Sep 2025',  author:'Mohammed Al Obaid',  note:'Initial framework standard — covers governance, risk management, compliance and technical security control domains.' }
        ]
      },
      'Information Security Policy': {
        current: 3,
        history: [
          { rev:3, date:'Mar 2026',  author:'Mohammed Al Obaid',  note:'Updated to reflect Saudi PDPL (Personal Data Protection Law) requirements; expanded cloud and SaaS security scope.' },
          { rev:2, date:'Oct 2025',  author:'Afnan Al Khabty',    note:'Added remote access security controls; mandated MFA for all corporate systems and privileged accounts.' },
          { rev:1, date:'Apr 2025',  author:'Mohammed Al Obaid',  note:'Initial policy release — establishes information security governance, responsibilities, and baseline controls.' }
        ]
      }
    }
  }
};
